// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ActivateFile(arg1: number): Promise<void>;

export function CreateMenu(): Promise<any>;

export function GetActiveFile(): Promise<any>;

export function GetAllFilesInMemory(): Promise<{ [key: number]: any }>;

export function GetAllFilesInformation(): Promise<Array<core.FileInformation>>;

export function IsFileAlreadyOpened(arg1: string): Promise<boolean>;

export function UpdateActiveFileContent(arg1: string): Promise<boolean>;
