// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateFile(arg1) {
    return window['go']['core']['EditorApplication']['ActivateFile'](arg1);
}

export function CreateMenu() {
    return window['go']['core']['EditorApplication']['CreateMenu']();
}

export function GetActiveFile() {
    return window['go']['core']['EditorApplication']['GetActiveFile']();
}

export function GetAllFilesInMemory() {
    return window['go']['core']['EditorApplication']['GetAllFilesInMemory']();
}

export function GetAllFilesInformation() {
    return window['go']['core']['EditorApplication']['GetAllFilesInformation']();
}

export function IsFileAlreadyOpened(arg1) {
    return window['go']['core']['EditorApplication']['IsFileAlreadyOpened'](arg1);
}

export function UpdateActiveFileContent(arg1) {
    return window['go']['core']['EditorApplication']['UpdateActiveFileContent'](arg1);
}
