// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ContextProvider is an autogenerated mock type for the ContextProvider type
type ContextProvider struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *ContextProvider) Execute() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

type mockConstructorTestingTNewContextProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewContextProvider creates a new instance of ContextProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContextProvider(t mockConstructorTestingTNewContextProvider) *ContextProvider {
	mock := &ContextProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
