// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	menu "github.com/wailsapp/wails/v2/pkg/menu"
)

// IMenuHelper is an autogenerated mock type for the IMenuHelper type
type IMenuHelper struct {
	mock.Mock
}

// CreateMenu provides a mock function with given fields:
func (_m *IMenuHelper) CreateMenu() *menu.Menu {
	ret := _m.Called()

	var r0 *menu.Menu
	if rf, ok := ret.Get(0).(func() *menu.Menu); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*menu.Menu)
		}
	}

	return r0
}

type mockConstructorTestingTNewIMenuHelper interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMenuHelper creates a new instance of IMenuHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMenuHelper(t mockConstructorTestingTNewIMenuHelper) *IMenuHelper {
	mock := &IMenuHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
