// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMenuOpsHelper is an autogenerated mock type for the IMenuOpsHelper type
type IMenuOpsHelper struct {
	mock.Mock
}

// CloseApplication provides a mock function with given fields:
func (_m *IMenuOpsHelper) CloseApplication() {
	_m.Called()
}

// CloseFile provides a mock function with given fields:
func (_m *IMenuOpsHelper) CloseFile() {
	_m.Called()
}

// NewFile provides a mock function with given fields:
func (_m *IMenuOpsHelper) NewFile() {
	_m.Called()
}

// OpenFile provides a mock function with given fields:
func (_m *IMenuOpsHelper) OpenFile() {
	_m.Called()
}

// SaveFile provides a mock function with given fields:
func (_m *IMenuOpsHelper) SaveFile() {
	_m.Called()
}

// SaveFileAs provides a mock function with given fields:
func (_m *IMenuOpsHelper) SaveFileAs() {
	_m.Called()
}

// ShowFileInfoModal provides a mock function with given fields:
func (_m *IMenuOpsHelper) ShowFileInfoModal() {
	_m.Called()
}

type mockConstructorTestingTNewIMenuOpsHelper interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMenuOpsHelper creates a new instance of IMenuOpsHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMenuOpsHelper(t mockConstructorTestingTNewIMenuOpsHelper) *IMenuOpsHelper {
	mock := &IMenuOpsHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
