// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEmptyFile(arg1) {
    return window['go']['internals']['EditorInternalApi']['AddEmptyFile'](arg1);
}

export function AddExistingFile(arg1) {
    return window['go']['internals']['EditorInternalApi']['AddExistingFile'](arg1);
}

export function ChangeFileContent(arg1, arg2) {
    return window['go']['internals']['EditorInternalApi']['ChangeFileContent'](arg1, arg2);
}

export function ChangeFileStatusToOpened(arg1) {
    return window['go']['internals']['EditorInternalApi']['ChangeFileStatusToOpened'](arg1);
}

export function CloseFile(arg1) {
    return window['go']['internals']['EditorInternalApi']['CloseFile'](arg1);
}

export function CreateEmptyFile() {
    return window['go']['internals']['EditorInternalApi']['CreateEmptyFile']();
}

export function CreateExistingFile(arg1, arg2) {
    return window['go']['internals']['EditorInternalApi']['CreateExistingFile'](arg1, arg2);
}

export function FindAnyFileInMemory() {
    return window['go']['internals']['EditorInternalApi']['FindAnyFileInMemory']();
}

export function FindOpenedFile() {
    return window['go']['internals']['EditorInternalApi']['FindOpenedFile']();
}

export function GetFilesInformation() {
    return window['go']['internals']['EditorInternalApi']['GetFilesInformation']();
}

export function InactivateAllFiles() {
    return window['go']['internals']['EditorInternalApi']['InactivateAllFiles']();
}

export function IsFileAlreadyOpened(arg1) {
    return window['go']['internals']['EditorInternalApi']['IsFileAlreadyOpened'](arg1);
}
