// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AddEmptyFile(arg1: any): Promise<any>;

export function AddExistingFile(arg1: any): Promise<any>;

export function ChangeFileContent(arg1: number, arg2: string): Promise<boolean>;

export function ChangeFileStatusToOpened(arg1: number): Promise<void>;

export function CloseFile(arg1: number): Promise<boolean>;

export function CreateEmptyFile(): Promise<any>;

export function CreateExistingFile(arg1: string, arg2: string): Promise<any>;

export function FindAnyFileInMemory(): Promise<any>;

export function FindOpenedFile(): Promise<api.FileApi>;

export function GetFilesInformation(): Promise<Array<api.InformationApi>>;

export function InactivateAllFiles(): Promise<void>;

export function IsFileAlreadyOpened(arg1: string): Promise<boolean>;
