// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCurrentFile(arg1) {
  return window['go']['frontend']['frontStruct']['CloseCurrentFile'](arg1);
}

export function GetFileTypeExtension(arg1) {
    return window['go']['frontend']['frontStruct']['GetFileTypeExtension'](arg1);
}

export function GetFileTypes() {
    return window['go']['frontend']['frontStruct']['GetFileTypes']();
}

export function GetFilesShortInfo() {
    return window['go']['frontend']['frontStruct']['GetFilesShortInfo']();
}

export function GetOpenedFile() {
    return window['go']['frontend']['frontStruct']['GetOpenedFile']();
}

export function SwitchOpenedFileTo(arg1) {
    return window['go']['frontend']['frontStruct']['SwitchOpenedFileTo'](arg1);
}

export function UpdateFileContent(arg1, arg2) {
    return window['go']['frontend']['frontStruct']['UpdateFileContent'](arg1, arg2);
}

export function UpdateFileInformation(arg1, arg2) {
    return window['go']['frontend']['frontStruct']['UpdateFileInformation'](arg1, arg2);
}
