// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from "../models";

export function CloseCurrentFile(arg1: number): Promise<void>;

export function GetFileTypeExtension(arg1: string): Promise<Array<api.KeyValuePairStruct>>;

export function GetFileTypes(): Promise<Array<api.KeyValuePairStruct>>;

export function GetFilesShortInfo(): Promise<Array<api.FileInfoStruct>>;

export function GetOpenedFile(): Promise<api.FileStruct>;

export function SwitchOpenedFileTo(arg1: number): Promise<void>;

export function UpdateFileContent(arg1: number, arg2: string): Promise<void>;

export function UpdateFileInformation(arg1: number, arg2: api.FileInfoUpdateStruct): Promise<void>;
