// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFileContent(arg1, arg2) {
    return window['go']['jsapi']['JsApiStruct']['ChangeFileContent'](arg1, arg2);
}

export function ChangeFileStatusToOpened(arg1) {
    return window['go']['jsapi']['JsApiStruct']['ChangeFileStatusToOpened'](arg1);
}

export function FindOpenedFile() {
    return window['go']['jsapi']['JsApiStruct']['FindOpenedFile']();
}

export function GetFilesInformation() {
    return window['go']['jsapi']['JsApiStruct']['GetFilesInformation']();
}
