// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseFile(arg1) {
  return window['go']['frontendapi']['FrontendApiStruct']['CloseFile'](arg1);
}

export function GetFileTypeExtension(arg1) {
  return window['go']['frontendapi']['FrontendApiStruct']['GetFileTypeExtension'](arg1);
}

export function GetFileTypes() {
  return window['go']['frontendapi']['FrontendApiStruct']['GetFileTypes']();
}

export function GetFilesShortInfo() {
    return window['go']['frontendapi']['FrontendApiStruct']['GetFilesShortInfo']();
}

export function GetOpenedFile() {
    return window['go']['frontendapi']['FrontendApiStruct']['GetOpenedFile']();
}

export function NewFile() {
    return window['go']['frontendapi']['FrontendApiStruct']['NewFile']();
}

export function SwitchOpenedFileTo(arg1) {
    return window['go']['frontendapi']['FrontendApiStruct']['SwitchOpenedFileTo'](arg1);
}

export function UpdateFileContent(arg1, arg2) {
    return window['go']['frontendapi']['FrontendApiStruct']['UpdateFileContent'](arg1, arg2);
}
