// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMenu() {
  return window['go']['application']['EditorApplication']['CreateMenu']();
}
