// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function CreateMenu():Promise<any>;

export function GetActiveFile():Promise<any>;

export function GetAllOpenedFile():Promise<{[key: number]: any}>;

export function GetAllOpenedFileDescriptors():Promise<Array<application.FileDescriptor>>;

export function MakeFileActive(arg1:number):Promise<void>;

export function UpdateFileContent(arg1:number,arg2:string):Promise<void>;
